### ISSUE TITLE
[FEAT] Script/process to import saved credit cards from Accept Hosted

### ISSUE THREAD

**Issue by erikhansen** [ParadoxLabs-Inc/authnetcim#12]
# :bulb: Feature request

## Feature Name

We’re working on migrating a client from a custom-built Authorize.net Magento extension (utilizing the Accept Hosted solution). Their Authorize.net account is not changing. Almost all of the functionality is working as expected with the exception of saved credit cards. In the custom-built solution, saved credit cards are displayed within an Authorize.net hosted iframe; even limited saved credit card data is not stored anywhere in Magento, unlike the Paradox Labs extension and the `paradoxlabs_stored_card` table. Furthermore, it looks like are storing the Authorize.net customer profile id in a different customer attribute.

In order to allow an existing customer to have their saved credit card data persist to the new extension, it seems like we need to do two things:

1. Migrate the profile_id to the Paradox Labs profile_id attribute (simple, we can handle this)
2. Populate the `paradoxlabs_stored_card` table (complex)

If you've encountered this before, do you have any suggestions for how to best populate the `paradoxlabs_stored_card` based on the cards stored in Authorize.net Accept Hosted? If not, we will discuss with our client and if we end up writing a script to populate the `paradoxlabs_stored_card` table, we'll share it here.

## Environment

<pre><code>
Authnetcim version: 2.4.4
Magento version: Adobe Commerce 2.4.4-p11
PHP version: 8.1
</code></pre>

**Comment by rhoerr** [comment]
You might be interested in https://github.com/ParadoxLabs-Inc/authnetcim/blob/master/Observer/ConvertLegacyStoredDataObserver.php -- it's not a perfect fit here, but might get you close. Our M1 version of the extension worked similarly, with data loaded primarily from Authnet. We changed it to on-site to reduce the performance/load of associated API calls. This observer was written to load such legacy customer profiles and import them into the stored card table. It looks at a specific Magento customer profile, and imports if (1) there is an authnetcim_profile_id, and (2) authnetcim_profile_version < 200 (defaults to 100). On completion, profile version is set to 200.

Note that the profile ID cache is not used nearly as much anymore -- it gets cleared any time API keys are changed, and Hosted ignores it at runtime either way to avoid duplication issues.

If you port the observer into a CLI command in some way, please feel free to submit a PR.

**Comment by erikhansen** [comment]
@rhoerr Thanks so much!

@kraken-chris Let's discuss this with the client. If they decide to have us spend time on this, can you post our final code/solution here in case others want to use it?
